repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ '--maxkb=1024' ]
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
      - id: pretty-format-json
        exclude: ^(.devcontainer/devcontainer.json|tests/trajectory/fixtures/)
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-executables-have-shebangs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  # Temporarily skip the scripts folder.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.2"
    hooks:
      - id: ruff
        exclude: ^(tests/|^pare/_archives/|^scripts/)
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        exclude: ^(tests/|^pare/_archives/|^scripts/)
        types: [ python ]
        require_serial: true
        verbose: true
