site_name: Proactive Agent Sandbox
repo_url: https://github.com/deepakn97/pas
site_url: https://deepakn97.github.io/pas
site_description: This repository contains code for the Proactive Goal Inference Agent project in collaboration with Apple.
site_author: Deepak Nathani
edit_uri: edit/main/docs/
repo_name: deepakn97/pas
copyright: Maintained by <a href="https://deepakn97.com">deepakn97</a>.

nav:
  - Home: index.md
  - Getting Started:
      - Scenario Authoring Guide: scenario_author_guide.md
      - Running Local LLM Models Guide: run_local_llm_model.md
      - Scenario Generation: scenario_generator.md
  - Architecture:
      - Visual Overview: architecture_visual.md
      - Environment Formalization: dec_pomdp_formulation.md
  - Apps:
      - App APIs Overview: apps/index.md
      - Adding a Stateful App: apps/adding_stateful_app.md
      - Contacts App: apps/contacts.md
      - Messaging App: apps/messaging.md
      - Email App: apps/email.md
      - Calendar App: apps/calendar.md
      - Cab Booking App: apps/cab.md
      - Shopping App: apps/shopping.md
      - Notes Taking App: apps/notes.md
  - API Reference:
      - Overview: modules.md
      - Environment: api/environment.md
      - Stateful Apps: api/apps.md
      - Scenarios: api/scenarios.md
      - Scenario Generator: api/scenario_generator.md

exclude_docs: |
  _plans/
  github_issues

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["pas"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepakn97/pas
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pas

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
